#!/bin/bash

TARGET_DIR=${1:?"Missing installation directory argument"}
# Resolve to absolute path for use in generated env script
mkdir -p "$TARGET_DIR"
TARGET_DIR=$(cd "$TARGET_DIR" && pwd)
ON_PATCH_FAIL="exit 1"

if test "x$2" == "x--debug-build";
then
LLVM_BUILD_MODE="-DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_ASSERTIONS=ON"
export CFLAGS=-O0
export CPPFLAGS=-O0
export CXXFLAGS=-O0
build_dir=llvm-build-Debug
else
export CFLAGS=-O3
export CPPFLAGS=-O3
export CXXFLAGS=-O3
LLVM_BUILD_MODE="-DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON"
build_dir=llvm-build-Release
fi

echo "### LLVM build mode: "$LLVM_BUILD_MODE

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
patch_dir=$script_dir/../patches
llvm_co_dir=release_22
llvm_branch=openasip-llvm-22-patched

mkdir -p $build_dir
cd $build_dir

function eexit {
   echo "$1"
   exit 1
}

# nproc is GNU coreutils and is absent on macOS/BSD.
function num_cpus {
    nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 1
}

function fetch_llvm {
    REV_TO_FETCH=$1
    if [ -n "$REV_TO_FETCH" ]; then
        REV_TO_FETCH="-r$REV_TO_FETCH"
    fi

    if ! test -d $llvm_co_dir;
    then
        git clone --single-branch --depth=1 --branch $llvm_branch https://github.com/cpc/llvmtce.git $llvm_co_dir\
            || eexit "Git clone $REV_TOFETCH from llvm failed"
    else
        cd $llvm_co_dir;
        git checkout $llvm_branch ||	eexit "checking out git branch failed"
        git fetch
        git reset --hard $llvm_branch || eexit "resetting --hard HEAD failed"
        cd ..;
    fi
}

fetch_llvm

cd $llvm_co_dir

# Apply LLVM patches before building. The i1 register-class fallback is needed for
# 64-bit TTA, where an i1 can land in a 64-bit result register (IRES0) that no
# register class declares i1 legal for. Without it the backend hits
# `assert(BestRC && "Couldn't find the register class")` while compiling.
# ⚠ This belongs to 64-bit support, which is upstream's own (incomplete) feature —
#   it is not part of the language-runtime work held back separately.
# ⛔ BOTH FAILURE PATHS ARE LOUD NOW, AND THEY DID NOT USED TO BE. While the patch
#    was held back, a missing file was a legitimate CONFIGURATION and `if [ -f ]`
#    with no else was the right shape. It ships now, so a missing file is a
#    DEFECT — and the old shape degraded silently into an unpatched compiler whose
#    first symptom is an assert deep inside somebody else's build, hours later and
#    nowhere near the cause.
# ⚠ The `|| echo WARNING` was the second silent path and the worse one: a failed
#   patch printed one line into a long log and carried on building. The
#   "may already be applied" excuse it offered is already ruled out by the grep
#   above, so reaching `patch` and failing is unambiguous.
i1_patch="$script_dir/../../patches/llvm-22-i1-regclass-fallback.patch"
if [ ! -f "$i1_patch" ]; then
    echo "### ERROR: LLVM patch not found: $i1_patch" >&2
    echo "###        64-bit TTA needs the i1 register-class fallback; without it" >&2
    echo "###        the backend asserts \"Couldn't find the register class\"" >&2
    echo "###        while compiling. Refusing to build a silently degraded LLVM." >&2
    exit 1
fi
if grep -q "needed for TTA targets where i1 values end up in 64-bit IRES0" llvm/lib/CodeGen/TargetRegisterInfo.cpp 2>/dev/null; then
    echo "### LLVM patch already applied."
else
    echo "### Applying LLVM patch (i1 register class fallback)..."
    if ! patch -p1 < "$i1_patch"; then
        echo "### ERROR: applying $i1_patch failed." >&2
        echo "###        The 'already applied' case is ruled out by the check above," >&2
        echo "###        so this is a real failure. Refusing to continue." >&2
        exit 1
    fi
fi

mkdir -p build
cd build

# -DLLVM_ENABLE_Z3_SOLVER=OFF due to the issue described in
# https://reviews.llvm.org/D54978#1390652
# You might also need to delete libz3-dev.
# This appears at least with Ubuntu 18.04.
cmake ../llvm/ -DLLVM_ENABLE_PROJECTS="clang;lld" \
    -G "Unix Makefiles" \
    $LLVM_BUILD_MODE\
    -DCMAKE_INSTALL_PREFIX=$TARGET_DIR \
    -DLLVM_TARGETS_TO_BUILD="X86;host" \
    -DLLVM_LINK_LLVM_DYLIB=TRUE \
    -DLLVM_ENABLE_RTTI=TRUE \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    || eexit "Configuring LLVM/Clang failed."
make -j$(num_cpus) || eexit "Building LLVM/Clang failed."
make install || eexit "Installation of LLVM/Clang failed."

# Generate tce-env.sh at the repository root
repo_root="$script_dir/../../.."
env_script="$repo_root/tce-env.sh"
# macOS ignores LD_LIBRARY_PATH; the dynamic loader reads DYLD_LIBRARY_PATH.
case "$(uname -s)" in
    Darwin) ld_path_var=DYLD_LIBRARY_PATH ;;
    *)      ld_path_var=LD_LIBRARY_PATH ;;
esac
cat > "$env_script" <<EOF
# OpenASIP environment — generated by install_llvm_22.sh
# Source this file before building or using OpenASIP:
#   source tce-env.sh
export PATH=$TARGET_DIR/bin:\$PATH
export $ld_path_var=$TARGET_DIR/lib:\${$ld_path_var:-}
export LDFLAGS=-L$TARGET_DIR/lib
EOF
echo "### Generated $env_script"
echo "###"
echo "### To set up your environment, run:"
echo "###   source $env_script"
echo "###"
